### PR TITLE
Add support for simple string manipulation

### PR DESCRIPTION
**Pull request by Fokko**
I would like to add support for concating strings

### CODE REVIEW

**Comment by Fokko** [comment]
Ah, documentation, keep forgetting that. I'll throw in some tomorrow 👍

**Comment by Fokko** [comment]
@asnare Thoughts?

**Comment by friso** [comment]
Is `concat_ws` what the rest of the world calls `join`?

**Comment by Fokko** [comment]
It is inspired by the SQL world: [SQL-Server](https://docs.microsoft.com/en-us/sql/t-sql/functions/concat-ws-transact-sql?view=sql-server-2017) [MySQL](https://dev.mysql.com/doc/refman/8.0/en/string-functions.html) [Postgres](https://www.postgresql.org/docs/9.6/static/functions-string.html) [R](https://spark.apache.org/docs/2.1.1/api/R/concat_ws.html)

A join is something else in SQL world, afaik 💃

**Comment by asnare** [comment]
I was avoiding `join` because that typically lets you specific start, end, and joining characters and is aimed at arrays which we don't really support: our situation is a fixed list of strings you want to append to each other.

In terms of API design, concatenation via a method on the provider is a little ambiguous for 'missing' values:

    foo().concat(bar()).concat(baz())

…is a little ambiguous if `foo()` or `bar()` happen to be missing since our style is to invalidate the sequence of what gets mapped. (Objective-C's `nil` reference and Groovy's elvis operator suffer from the same problem.)

So the idea was to hoist it out into a static method that simply concatenates all the values together. I didn't want to call it `join` because then the whole separator discussion starts up, which can be avoided because we normally have a static list of stuff to join:

    concat(foo(), bar(), baz())

Literals are still a pain but solvable.

PS. Not a fan of the `concat_ws()` name  ;)

**Pull request closed without merging**
