### PR TITLE
Implement GCS retry

### PR DESCRIPTION
**Pull request by Fokko**
Currently we see errors from the GCS side. We would like to implement a retry mechanism in case we get a 50x response. Currently we're testing this branch in our staging environment.

### CODE REVIEW

**Comment by Fokko** [comment]
@asnare @friso Can we get this merged into master?

I got some errors of Google, and the requests are retried and succeeded:
```
2018-02-14 08:59:38.039Z [Google Cloud Storage Flusher [gcs] - 0] ERROR [GoogleCloudStorageFileManager]: Received unexpected response from Google Cloud Storage. Response status code: 503. Response body: {
 "error": {
  "errors": [
   {
    "domain": "global",
    "reason": "backendError",
    "message": "Backend Error"
   }
  ],
  "code": 503,
  "message": "Backend Error"
 }
}

2018-02-14 08:59:38.961Z [Google Cloud Storage Flusher [gcs] - 0] ERROR [GoogleCloudStorageFileManager]: Retrying POST call (https://www.googleapis.com/upload/storage/v1--------vro.part) attempt to GCS API. Attempt #1
java.io.IOException: Received unexpected response (503) from Google Cloud Storage.
	at io.divolte.server.filesinks.gcs.GoogleCloudStorageFileManager.throwIOExceptionOnErrorResponse(GoogleCloudStorageFileManager.java:432)
	at io.divolte.server.filesinks.gcs.GoogleCloudStorageFileManager.parseResponse(GoogleCloudStorageFileManager.java:358)
	at io.divolte.server.filesinks.gcs.GoogleCloudStorageFileManager.lambda$googlePost$2(GoogleCloudStorageFileManager.java:379)
	at net.jodah.failsafe.SyncFailsafe.call(SyncFailsafe.java:145)
	at net.jodah.failsafe.SyncFailsafe.get(SyncFailsafe.java:56)
	at io.divolte.server.filesinks.gcs.GoogleCloudStorageFileManager.googlePost(GoogleCloudStorageFileManager.java:371)
	at io.divolte.server.filesinks.gcs.GoogleCloudStorageFileManager.access$1100(GoogleCloudStorageFileManager.java:60)
	at io.divolte.server.filesinks.gcs.GoogleCloudStorageFileManager$GoogleCloudStorageDivolteFile.writeBufferAndComposeParts(GoogleCloudStorageFileManager.java:244)
	at io.divolte.server.filesinks.gcs.GoogleCloudStorageFileManager$GoogleCloudStorageDivolteFile.sync(GoogleCloudStorageFileManager.java:214)
	at io.divolte.server.filesinks.FileFlusher.sync(FileFlusher.java:212)
	at io.divolte.server.filesinks.FileFlusher.possiblySyncAndOrRoll(FileFlusher.java:203)
	at io.divolte.server.filesinks.FileFlusher.handleHeartbeatWithHealthyFileSystem(FileFlusher.java:137)
	at io.divolte.server.filesinks.FileFlusher.lambda$heartbeat$0(FileFlusher.java:131)
	at java.util.Optional.map(Optional.java:215)
	at io.divolte.server.filesinks.FileFlusher.heartbeat(FileFlusher.java:131)
	at java.util.Optional.orElseGet(Optional.java:267)
	at io.divolte.server.processing.ProcessingPool.lambda$microBatchingQueueDrainerWithHeartBeat$5(ProcessingPool.java:137)
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1626)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
and:
```
2018-02-13 19:11:51.546Z [Google Cloud Storage Flusher [gcs] - 0] ERROR [GoogleCloudStorageFileManager]: Received unexpected response from Google Cloud Storage. Response status code: 502. Response body: <!DOCTYPE html>
<html lang=en>
  <meta charset=utf-8>
  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
  <title>Error 502 (Server Error)!!1</title>
  <style>
    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}
  </style>
  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>
  <p><b>502.</b> <ins>That?s an error.</ins>
  <p>The server encountered a temporary error and could not complete your request.<p>Please try again in 30 seconds.  <ins>That?s all we know.</ins>

2018-02-13 19:11:52.565Z [Google Cloud Storage Flusher [gcs] - 0] ERROR [GoogleCloudStorageFileManager]: Retrying POST call (https://www.googleapis.com/-------------avro.part) attempt to GCS API. Attempt #1
java.io.IOException: Received unexpected response (502) from Google Cloud Storage.
	at io.divolte.server.filesinks.gcs.GoogleCloudStorageFileManager.throwIOExceptionOnErrorResponse(GoogleCloudStorageFileManager.java:432)
	at io.divolte.server.filesinks.gcs.GoogleCloudStorageFileManager.parseResponse(GoogleCloudStorageFileManager.java:358)
	at io.divolte.server.filesinks.gcs.GoogleCloudStorageFileManager.lambda$googlePost$2(GoogleCloudStorageFileManager.java:379)
	at net.jodah.failsafe.SyncFailsafe.call(SyncFailsafe.java:145)
	at net.jodah.failsafe.SyncFailsafe.get(SyncFailsafe.java:56)
	at io.divolte.server.filesinks.gcs.GoogleCloudStorageFileManager.googlePost(GoogleCloudStorageFileManager.java:371)
	at io.divolte.server.filesinks.gcs.GoogleCloudStorageFileManager.access$1100(GoogleCloudStorageFileManager.java:60)
	at io.divolte.server.filesinks.gcs.GoogleCloudStorageFileManager$GoogleCloudStorageDivolteFile.writeBufferAndComposeParts(GoogleCloudStorageFileManager.java:244)
	at io.divolte.server.filesinks.gcs.GoogleCloudStorageFileManager$GoogleCloudStorageDivolteFile.sync(GoogleCloudStorageFileManager.java:214)
	at io.divolte.server.filesinks.FileFlusher.sync(FileFlusher.java:212)
	at io.divolte.server.filesinks.FileFlusher.possiblySyncAndOrRoll(FileFlusher.java:203)
	at io.divolte.server.filesinks.FileFlusher.process(FileFlusher.java:115)
	at io.divolte.server.processing.ItemProcessor.process(ItemProcessor.java:32)
	at io.divolte.server.processing.ProcessingPool.lambda$microBatchingQueueDrainerWithHeartBeat$5(ProcessingPool.java:139)
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1626)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by friso** [comment]
@Fokko Love their mixed use of JSON and HTML response.

**Comment by Fokko** [comment]
I believe the oauth stuff returns html, and the actual GCS API is json 👍

**Comment by Fokko** [comment]
Nice, it looks much nicer with the `IOFunction`. I'll make the `RetryPolicy` configurable.

**Comment by Fokko** [comment]
@asnare One question regarding the refactoring. I'm missing the:
```
finally {
  stream.close();
}
```
For example, if [the `MAPPER` throws](https://github.com/divolte/divolte-collector/blob/master/src/main/java/io/divolte/server/filesinks/gcs/GoogleCloudStorageFileManager.java#L364) an `IOException`, the exception will propagate and a retry will be initiated. But the stream will never be explicitly closed. Not explicitly closing an IO stream does make me a bit nervous, what are your thoughts on this?

Cheers, Fokko

**Comment by asnare** [comment]
@Fokko I refactored it to use try-with-resources, which is preferable to closing in a `finally` block.

I just skimmed the file, and a few others were missing. Also pushed.

**Comment by asnare** [comment]
I just realised that at the moment I don't think we differentiate between temporary and permanent errors. The [GCS docs](https://cloud.google.com/storage/docs/json_api/v1/status-codes#http-status-and-error-codes) explicitly list the status codes on which we should retry: 500, 502 & 503

For the rest I'd prefer to fail fast.

The way I'd approach this is to:

1. Subclass `IOException` with `RetriableIOException`, to be thrown in the situations where we should retry.
2. For the rest throw `IOException` like we do now.
3. Configure the retry thing to only retry on `RetriableIOException`.

Thoughts?

**Comment by Fokko** [comment]
@asnare Personally I'm a big fan of the KISS principle, so leave it as is, unless there is a reason that we've seen in practice that we would need this. But if you like this, I'm fine implementing this. @friso had a similar construction:
https://github.com/friso/divolte-collector/blob/7c245dc94588f516f191535cebcf182df7355dc9/src/main/java/io/divolte/server/filesinks/gcs/GoogleCloudStorageFileManager.java#L411-L417

**Comment by Fokko** [comment]
One last questions about the threading model of Divolte. Would it be wise to make a local copy of the position variable, and then subtract the processed messages from the position variable, instead of setting it to zero. It could that a messages is being appended to the buffer, between sending, and clearing the buffer. What are your thoughts? Relevant code:
https://github.com/Fokko/divolte-collector/blob/fd-retry-using-failsafe/src/main/java/io/divolte/server/filesinks/gcs/GoogleCloudStorageFileManager.java#L234-L263

**Comment by friso** [comment]
A single instance of `GoogleCloudStorageFileManager` and transitively `GoogleCloudStorageDivolteFile` should only be touched by a single thread.

**Comment by friso** [comment]
@Fokko This code now uses a fraction for jitter, whereas the [GCS docs](https://cloud.google.com/storage/docs/exponential-backoff) describe a random jitter to be added to the outcome.

**Comment by friso** [comment]
Wouldn't you rather use the [`withJitter(...)` overload](http://jodah.net/failsafe/javadoc/net/jodah/failsafe/RetryPolicy.html#withJitter-long-java.util.concurrent.TimeUnit-) that takes a fixed maximum jitter with a time unit?

**Comment by Fokko** [comment]
I've replaced the `withJitter(double)` overload to  `withJitter(Long, TimeUnit)` as @friso prefers. I've removed the `withJitter(double)` completely since you cannot initialise with `0.0` https://github.com/jhalterman/failsafe/pull/123

**Comment by asnare** [comment]
I've just pushed some changes. These include:

 - Nesting the retry settings as a group and renaming the individual settings to match those we use for Google Pub/Sub. (The underlying implementation differs, but most of the knobs to tweak are the same.)
 - The jitter can now be specified as _either_ a factor or a duration (but not both). Although Google suggests using the duration, the research seems to suggest that using a factor is probably better.
 - The defaults now match the [example algorithm suggested by Google](https://cloud.google.com/storage/docs/exponential-backoff).

Still missing:

 - Some tests.
 - Updating the docs to match the changes I've made.

**Comment by asnare** [comment]
As a minor aside, the whole jitter thing can't be _that_ important: I noticed when figuring out the `RetrySettings` thing for Google Pub/Sub that although there are some jitter knobs the implementation ignores them totally.

**Comment by asnare** [comment]
I've just pushed some doc and test updates, and think it's now ready to merge.

**Pull request merged**
