### PR TITLE
fix classpath for the RPM version

### PR DESCRIPTION
**Pull request by rweverwijk**
The current 0.6 version of the RPM ships a broken startscript. there is a version conflict on a guava class. This PR fixes the issue.

### CODE REVIEW

**Comment by rweverwijk** [comment]
seems that there is an unshaded version of the closure-compiler. By using this version there is no longer a conflict on runtime.

**Comment by friso** [comment]
Ideally, when messing with the dependencies anyway, update all of them to latest versions, so we don't run stale.

**Comment by asnare** [comment]
So I haven't had time to look at this, but I want to check the way the startup script assembles the class-path list. In particular, I'd like to know:

- if it does it in a way that is deterministic
- how many duplicate classes we have (I assume this isn't zero)

Essentially, if it's using `find` without sorting the jars by name then the class path will be non-deterministic and vary across systems depending on the vagaries of the filesystem involved. (Normally on a single system it'll be deterministic, albeit with an arbitrary order.)

If it's using shell globbing (`*`) then I _think_ it should be sorted in a stable manner.

This goes to understanding when the conflict will be triggered, and knowing that it's properly fixed.

**Comment by rweverwijk** [comment]
on mac it is alphabetically ordered.

**Pull request merged**
