### PR TITLE
Support (and test) quirks mode in browsers

### PR DESCRIPTION
**Pull request by asnare**
This pull request:

 - Fixes an issue when running in quirks mode (Issue #74)
 - Updates the selenium-based tests to also test quirks mode.

### CODE REVIEW

**Comment by friso** [comment]
Did SL tests run successfully?

**Comment by asnare** [comment]
The run was interrupted, so I've started a new run just now. I'll keep you posted.

**Comment by friso** [comment]
OK. If that passes (on par with previous runs), we can merge this.

**Comment by asnare** [comment]
It looks like IE6 on XP still fails in quirks mode. That's not a regression, but rather indicates the fix in this pull request is incomplete.

(The cookie-setting test also failed in strict mode for IE6/XP and iOS 7.1. Hmmm.)

**Comment by friso** [comment]
SL can be pretty flakey. Especially on mobile devices. I manually tested iOS 7.1 (I don't upgrade much); it works.

On SL there was already an issue with IE6/XP, because of issues with the Selenium driver. In live traffic, we don't see that combination much (if at all) anymore. Not sure it that holds for all geographies, but we have no means of verifying that.

**Pull request merged**
